version: '3'

services:
  web:
    image: python:3.8-alpine
    container_name: dockerception
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && python app.py"

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3





